### ISSUE TITLE
PitchRx 1.8.4 Update code to incorporate trailing slash requirements for new AWS MLBAM repo for 2017 and newer data

### ISSUE THREAD

**Issue by jrbattles** [fire-ants/mlb-analytics-ant-datafresh#3]
This does NOT work.
[http://gd2.mlb.com/components/game/mlb/year_2017/month_04/day_02/](http://gd2.mlb.com/components/game/mlb/year_2017/month_04/day_02/)

This does work.

[http://gd2.mlb.com/components/game/mlb/year_2017/month_04/day_02](http://gd2.mlb.com/components/game/mlb/year_2017/month_04/day_02)

As described here....
https://github.com/cpsievert/pitchRx/issues/57

**Comment by jrbattles** [comment]
Incorporate new PitchRx 1.8.4

**Comment by dancohen21** [comment]
1.8.4 has been vendored and is installed by cf push
